### Get path where libraries have been installed/ path to conda environment that should be uses

## from configuraiton file
env_configs = read.csv('../conda_environment/Environment_Configs.csv', sep = ',')
path_to_conda_env = env_configs$value[env_configs$parameter == 'conda_env_path']
path_to_conda_env = paste0(path_to_conda_env, '/lib/R/library')
print(path_to_conda_env)


### Libraries for all the project scripts
#library('generics', lib.loc = path_to_conda_env)
#library('nichenetr',  lib.loc = path_to_conda_env)
library(igraph, lib.loc = path_to_conda_env)
library(scater, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(Seurat, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(cowplot, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(HDF5Array, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(zellkonverter, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(reticulate, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(SeuratData, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(SeuratDisk, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)  # conversion hd5f to seurat file
library(stringr, quietly = TRUE, verbose = FALSE, lib.loc = path_to_conda_env)
library(gridExtra, lib.loc = path_to_conda_env)
library(dplyr, lib.loc = path_to_conda_env)
#library(ggpubr, lib.loc = path_to_conda_env)
library(plotly, lib.loc = path_to_conda_env)
library(muscat, lib.loc = path_to_conda_env)
library(limma, lib.loc = path_to_conda_env)
library(DESeq2, lib.loc = path_to_conda_env)
library(org.Hs.eg.db, lib.loc = path_to_conda_env) 
library(clusterProfiler, lib.loc = path_to_conda_env)
library(data.table, lib.loc = path_to_conda_env)
library(MOFA2, lib.loc = path_to_conda_env)
library(ggraph, lib.loc = path_to_conda_env)
library(Hmisc, lib.loc = path_to_conda_env)
library(graphlayouts, lib.loc = path_to_conda_env)
library(GGally, lib.loc = path_to_conda_env)
library(rstatix, lib.loc =path_to_conda_env)
library(ggraph, lib.loc = path_to_conda_env)
library(graphlayouts, lib.loc = path_to_conda_env)
reticulate::py_config()  
#library('ggpubr',  lib.loc = path_to_conda_env)
library('mvtnorm', lib.loc = path_to_conda_env)
library(MOFA2, lib.loc = path_to_conda_env)
#library(tidyverse, lib.loc = path_to_conda_env)
library(corrplot, lib.loc = path_to_conda_env)
library('visNetwork', lib.loc = path_to_conda_env)
#library('networkD3', lib.loc = path_to_conda_env)
library(network, lib.loc = path_to_conda_env)
library('colorspace', lib.loc = path_to_conda_env)
library(muscat, lib.loc = path_to_conda_env)
library(limma, lib.loc = path_to_conda_env)
library(DESeq2, lib.loc = path_to_conda_env)
library(enrichplot, lib.loc = path_to_conda_env)
library(DOSE, lib.loc = path_to_conda_env)
library('ggnewscale', lib.loc = path_to_conda_env)
library(ggupset, lib.loc = path_to_conda_env)
library(ComplexUpset, lib.loc = path_to_conda_env)
library(UpSetR,lib.loc = path_to_conda_env)
library(gdata, lib.loc = path_to_conda_env)
library('stringr', lib.loc = path_to_conda_env)
library('reshape2', lib.loc = path_to_conda_env)
#library('dplyr', lib.loc = path_to_conda_env)
#library("pathview", lib.loc = path_to_conda_env)
library(ReactomePA, lib.loc = path_to_conda_env)
library(MOFAdata, lib.loc = path_to_conda_env)
library(reactome.db, lib.loc = path_to_conda_env)
library(graphite, lib.loc = path_to_conda_env)
library(sva, lib.loc = path_to_conda_env)
library(patchwork, lib.loc = path_to_conda_env)
#library(caret, lib.loc = path_to_conda_env)
library(rstatix, lib.loc = path_to_conda_env)
library(pROC, lib.loc = path_to_conda_env)
library(glmnet, lib.loc = path_to_conda_env)
library(nnet, lib.loc = path_to_conda_env)
library(dfidx, lib.loc = path_to_conda_env)
library(mlogit, lib.loc = path_to_conda_env)
#library(modelr, lib.loc = path_to_conda_env)
library('cvAUC', lib.loc = path_to_conda_env)
library(fossil, lib.loc = path_to_conda_env)
library(ggrepel, lib.loc = path_to_conda_env)
library(plotROC, lib.loc = path_to_conda_env)
library(factoextra, lib.loc = path_to_conda_env)
library("ComplexHeatmap", lib.loc = path_to_conda_env)
library(compositions, lib.loc = path_to_conda_env)
#library('nichenetr',  lib.loc = path_to_conda_env)
library('circlize', lib.loc = path_to_conda_env)
library('ggpubr', lib.loc = path_to_conda_env)
library('lisi', lib.loc = path_to_conda_env)
library('multcomp', lib.loc = path_to_conda_env)
library('ggforce', lib.loc = path_to_conda_env)
library('ROCit', lib.loc = path_to_conda_env)